### ISSUE TITLE
Validating empty string or zero integer

### ISSUE THREAD

**Issue by mandeepkhatry** [go-ozzo/ozzo-validation#100]
For eg. 
validation.Validate(data, validation.Min(10))  (data here is an integer in my case) doesn't validate zero integer. Is there a way in which I can validate zero integer? So that it results "must be no less than 10".

**Comment by maratori** [comment]
@mandeepkhatry As doc says you should use `Required`.
https://github.com/go-ozzo/ozzo-validation/blob/master/minmax.go#L42
> // An empty value is considered valid. Please use the Required rule to make sure a value is not empty.

**Comment by qiangxue** [comment]
@maratori Thank you for helping answer the question!
