### ISSUE TITLE
 How do I set up i18n.

### ISSUE THREAD

**Issue by im-zhangxi** [go-ozzo/ozzo-validation#102]
For the error message, I need to switch languages.
Like translations.

**Comment by erdaltsksn** [comment]
You can use `Error()` method to customize the message. Of course, you need to implement the i18n by yourself.

`validation.Required.Error("Your custom/translated message")`

You may check my implementation at [erdaltsksn/gonca](https://github.com/erdaltsksn/gonca).

```
      1 .
      2 ├── messages
      3 │   ├── en.yaml
      4 │   └── tr.yaml
      5 └── models.go
      6 
```

**models.go:**
```go
validation.Required.Error(i18n.Translate("errValidateModelRequired"))
```

**en.yaml:**
```yaml
errValidateModelRequired: "Cannot be blank"
```

**tr.yaml:**
```yaml
errValidateModelRequired: "Boş bırakılamaz"
```

**Comment by qiangxue** [comment]
@erdaltsksn Thank you for sharing your solution!
