### ISSUE TITLE
day / time validation

### ISSUE THREAD

**Issue by dwoske** [go-ozzo/ozzo-validation#11]
Suggest adding Date / Time validation rules, with a way to specify the format of the date, perhaps copy the https://golang.org/pkg/time/#Time.Format layout.

**Comment by qiangxue** [comment]
Are you looking for a string validator? Will regex rule work for you?

**Comment by qiangxue** [comment]
Or are you looking for a rule that validates the range of a date?

**Comment by dwoske** [comment]
I suppose a regex can work.. something along these lines http://www.pelagodesign.com/blog/2009/05/20/iso-8601-date-validation-that-doesnt-suck/  .. lots of other versions of a date regex about as well.
