### ISSUE TITLE
translation is not work

### ISSUE THREAD

**Issue by qfly888** [go-ozzo/ozzo-validation#112]
Translation error does not work. I set the error message, but it does not work. The code is as follows:
`validation.ErrRequired = validation.NewError("validation_required", "不能为空")`

I tried to change the source code
required.go line 34-44
` 
func (r RequiredRule) Validate(value interface{}) error {
	
    if r.condition {
		value, isNil := Indirect(value)
		if r.skipNil && !isNil && IsEmpty(value) || !r.skipNil && (isNil || IsEmpty(value)) {
			r.err = ErrRequired  // add this code is correct
			return r.err
		}
	}
	return nil
}`

> r.err = ErrRequired  // add this code is correct

I'm not sure if my method is wrong or the program is wrong. I hope to get your answer

**Comment by qiangxue** [comment]
Thanks for reporting the issue. It should be fixed now.
