### ISSUE TITLE
how to stop sending test log report?

### ISSUE THREAD

**Issue by hnazari1990** [go-ozzo/ozzo-validation#117]
Hi
Thank you for your great library, it's very helpful.
Please let me know how I can configure the validation package to prevent sending the test logs to the server each time that I run my tests.
<img width="739" alt="Screen Shot 2020-07-10 at 2 56 49 PM" src="https://user-images.githubusercontent.com/16572317/87145037-f4ce7500-c2bd-11ea-9437-fac914701803.png">

**Comment by qiangxue** [comment]
May be related to your particular environment. You may want to exclude vendor scripts from your tests. Closing this issue as it is not an issue of this project.
