### ISSUE TITLE
Allow a rule closure access to StructField

### ISSUE THREAD

**Issue by freb** [go-ozzo/ozzo-validation#118]
I needed the ability to access a field's `reflect.StructField` before deciding which rules to apply to the field in struct validation. I obviously couldn't change the signature of rules which operate on the struct fields' values. The approach I took was to implement a new struct validation method (`ValidateStructFunc`), which takes a modified `FieldRules` (`FieldRulesFunc`) which receives the `StructField` as an input and returns the list of rules.

My particular use was to perform validation only if a struct field matched a [FieldMask](https://godoc.org/google.golang.org/genproto/protobuf/field_mask), which requires access to the field's struct tags.

I ended up forking the library since there were a number of internal types and functions that `validateStruct` uses that I didn't want to copy. Another option could have been to perform the validation manually, but I decided I wanted to keep the process as close as possible to the validation in other areas of my application.

I wanted to present it here in case it is something you think could be generally useful. If so, I'm happy to add some tests and open a pull request. Otherwise feel free to close this issue.

[My implementation](https://github.com/go-ozzo/ozzo-validation/compare/master...aerissecure:master)

Thanks for the great library.

**Comment by qiangxue** [comment]
Thanks for sharing your work! Does [Conditional Validation](https://github.com/go-ozzo/ozzo-validation#conditional-validation) work for your use case?

**Comment by freb** [comment]
Conditional Validation could definitely work. I probably should have taken a harder look it in the beginning, but I think I was trying to avoid the extra reflection and re-implementing the `findStructField` func. I also wanted to avoid passing the struct and field twice.

After doing it with conditional validation, this is what I end up with:

```go
  err := validation.ValidateStruct(a,
    validation.Field(&a.CreatedAt, validation.When(InMask(a, &a.CreatedAt, filter, namer), UndeletableRule)),
    // other fields...
  )
```

This is with the forked version:

```go
  err := validation.ValidateStructFunc(a,
    validation.FieldFunc(&a.CreatedAt, Fieldmask(filter, namer, UndeletableRule)),
    // other fields...
  )
```

With the forked version, I don't have to reflect and loop the struct fields for each field I want to check since it uses the StructField already available in `validateStruct`. The performance difference is small, there is less code, and it doesn't require any library alterations. I think conditional validation is the way to go.

Thanks for encouraging me take a second look at that.
