### ISSUE TITLE
Suggestion for library improvement

### ISSUE THREAD

**Issue by msaron** [go-ozzo/ozzo-validation#12]
This library is great. I had been looking for a library that would be as elegant and flexible as the NodeJS [Joi](https://github.com/hapijs/joi) library developed by Walmart for their [hapijs](https://hapijs.com/) framework and I found this library that was the closest thing to the Joi library. I would like to make the following suggestions to improve the library. 

- Field names passed in to the validator should be pointer based instead of a string. For example, use &c.Name instead of "Name". This would move the error for using the wrong field name from a runtime error to a compile time error.
- Incorporate the validation rules from the [goburrow](https://github.com/goburrow/validator/) validator into the go-ozzo validator which have been really thought out and powerful. For example goburrow has the "min" validation rule, which applies the rule depending upon what has been passed in. If a string is passed in, then it checks for the minimum length. If a slice has been passed in, then it checks for the length of the array. If an integer has been passed in, then it checks if the value is equal to or greater than the min value. And so on...

Thanks for a great library!

**Comment by qiangxue** [comment]
Thank you for your suggestions!

The usage design of Joi looks very neat to me. I will see how we can borrow some of its ideas here.

I totally agree with you about your comments on &c.Name instead of "Name". I have come up with a solution and will find time to implement it.

Regarding goburrow and other similar validation packages in golang, the main thing I don't like is that they rely on struct tags to define validation rules. It seems handy initially, but will quickly go out of control (hard to debug, error prone when working with many rules, hard to extend). It is also the main reason behind this package.

**Comment by msaron** [comment]
For the goburrow library, I was suggesting to refactor and incorporate the logic of the validations that the library has and convert it to your library format, not to use tags. It would enhance the already great built-in capabilities of your library. Thank you!

**Comment by qiangxue** [comment]
I see. Could you list which validators in goburrow may be considered?
For string/array length validation, we already have the Length validator.
And for numeric min/max validation, we have the Range validator.

**Comment by msaron** [comment]
Here is my recommendation. If the goburrow min and max validations are refactored and incorporated into go-ozzo, you could eliminate the following validations in go-ozzo.

- Range
- Length

For example in the go-ozzo Range validation, I see the following comment:
`Note that the value being checked and the boundary values must be of the same type.`

The elegance of the goburrow implementation is that the min and max validation apply to all data types including arrays, maps, slices, strings, and all types of integers and floats. Thus, one validation rule rules them all for min. Similarly for the max validation.  In addition, the value being checked and the boundary values do not need to be of the same type. In go-ozzo, you need to apply a range which is not intuitive if you only want to check the min or only the max value. 

With the goburrow implementation, if you want to check a range, you provide both the min and the max value. If you only want to check the min, you only apply the min validation. And so on...

 I just think the goburrow implementation is very elegant. However, I did not like the tag based validation, thus my suggestion to refactor it into the go-ozzo way of doing the validation.

**Comment by msaron** [comment]
If we could refactor the goburrow validation rules into go-ozzo and change the field names from being a string to a pointer, I think this would be the best library out there for validations!

**Comment by msaron** [comment]
One other suggestion I would like to make is that there should be an option to use the json struct tag field names instead of creating a new validation tag. This would save a lot of typing.

**Comment by qiangxue** [comment]
goburrow's notEmpty validator is equivalent to ozzo's `Required` validator. See more details [here](https://github.com/go-ozzo/ozzo-validation#required-vs-not-nil) for why ozzo also provides a `NotNil` validator.

> One other suggestion I would like to make is that there should be an option to use the json struct tag field names instead of creating a new validation tag. This would save a lot of typing.

"For example, you may set validation.ErrorTag to be "json" if you want to reuse the JSON field names as error field names."

**Comment by msaron** [comment]
Oh, I did not realize that. That works! Thanks!

**Comment by qiangxue** [comment]
I realized that if we want to use &c.Name instead of "Name" when declaring validation rules, we still need to specify a field name to receive the potential validation error (e.g. to serialize the validation errors of a struct, you would want to have a map of errors, each associated with a field name).

If such a error map is not desired, you may readily use `Rules` to validate field values.

**Comment by msaron** [comment]
We do need an error map. Can we use reflect just to get the field name? That way we can do away with a string field name and catch any errors during compile time. I personally use the json field names as my application is an api and I need to send back error messages for the same field names as they came in.

**Comment by qiangxue** [comment]
Unfortunately, by &s.field alone it's impossible to obtain the
corresponding struct field information through reflection.

**Comment by nsf** [comment]
I have a similar library here, it's not publically available, but I can tell that we indeed use pointers instead of field names. And you can totally extract the name if you pass in the pointer to the struct itself as well. So, something like:

```go
valid.Validate(&a).
  Mandatory(&a.FirstName, valid.MaxLength(250)).
  Mandatory(&a.LastName, valid.MaxLength(250)).
  Mandatory(&a.Email, valid.Email).
  Optional(&a.Age, valid.PositiveInteger).
  Done()
```

This way you can simply scan the struct at `&a` and create a map of all field addresses. Using that map you can lookup each individual field when necessary. Also you can ensure that all fields were visited by a validator - very important feature. In our case struct usually is a JSON input struct, so we extract field names from struct tags for error reporting.

Very nice library btw.

**Comment by msaron** [comment]
@nsf Any reason your library is not publicly available? Apart from go-ozzo, there is nothing like this out there and your library would generate more ideas on how to improve validation without using tags.

**Comment by nsf** [comment]
It's part of a proprietary project.

**Comment by msaron** [comment]
I use the [chi](https://github.com/pressly/chi) library router for my applications. In talking about validation and suggesting the go-ozzo library to the author of the chi library, they have [commented](https://github.com/pressly/chi/issues/84) that they are developing a non-tag based and very simple library for request and response payloads validation for chi/render. Can't wait to see what they come up with. I believe they are waiting for Golang 1.8 to be released before they will publish the validation library, but I am not sure.

**Comment by qiangxue** [comment]
@nsf Thank you for your comments! The idea you described is very clever. I really like it and will try to implement it here. Thanks!

@msaron Regarding request/response payload handling, my other project ozzo-routing takes [this way](https://github.com/go-ozzo/ozzo-routing#reading-request-data) and can be readily used together with ozzo-validation.

**Comment by qiangxue** [comment]
I have implemented the new struct validation syntax: https://gist.github.com/qiangxue/580c98c1f59e97849bc8b626c2d3245e. Could you take a look before I commit it? Thanks.

**Comment by msaron** [comment]
@qiangxue Just a feedback on how I am planning to use your library. As mentioned above, I am coming in from a NodeJS background where I was using the [hapijs/joi](https://github.com/hapijs/joi) library for all my validations, but your library is even more powerful than that because it allows me to dynamically inject valid values based on the userid in the request. 

I am creating a middleware where I am going to pass a map[requestInput string]interface{} to each request that I want to validate and which implements your validate() method. The requestInput keys will be one of the following types: 

- headers
- query
- params
- payload (or body)
- auth

The middleware will process the validation for each input. The request handler will only be called if all validations pass. This ensures that when the request reaches the handler, you can rest assured that everything is clean and validated. For each input that has been processed by the middleware, it will inject that struct into the context so that it is available to the handler. 

Thank you for a beautiful library! I just love beautiful code.

**Comment by qiangxue** [comment]
@msaron Thank you for your compliments. I'm glad this library is useful for you. Your middleware idea sounds great to me. It should be very useful. I'm not sure if I will create this one for ozzo-routing. It's easy to create one specifically for a project, but to create a generic solution it involves quite some effort. If you have a first version, I will be more than happy to take a look and see how it may be generalized. Thanks.
