### ISSUE TITLE
Validation.In(1,2) not working for uint field types

### ISSUE THREAD

**Issue by khanakia** [go-ozzo/ozzo-validation#124]
Hello ,
I have the below code and i have fieldtype is `uint` and validator is not validating as you can see below example there should be no error but it gives error even if i pass the correct value

https://play.golang.org/p/zlOTTem_99g

```
package main

import (
	"fmt"
	"github.com/go-ozzo/ozzo-validation"
)

type Item struct {
	StatusID uint `json:"statusId"`
}

func (a Item) Validate() error {
	return validation.ValidateStruct(&a,
		validation.Field(&a.StatusID, validation.Required, validation.In(1, 2)),
	)
}

func main() {
	a := Item{
		StatusID: 1,
	}
	err := a.Validate()
	fmt.Println(err)
}
```

**Comment by qiangxue** [comment]
As explained in the doc, the `In` validator uses `reflection.DeepEqual` to do the value comparison, which requires the value types to be  the same. So to fix your problem, use `validation.In(uint(1), uint(2))`
