### ISSUE TITLE
validation.When() function missing?

### ISSUE THREAD

**Issue by jeffmvr** [go-ozzo/ozzo-validation#125]
Hi,

First, thanks for the great library.

Has this library changed to remove the validation.When() function, or is there a new way to do conditional validation? This seems to no longer be present in the latest code yet is still documented as existing in the README.

**Comment by qiangxue** [comment]
It's here: https://github.com/go-ozzo/ozzo-validation/blob/master/when.go#L4

**Comment by jeffmvr** [comment]
Thanks.

My issues was running 

`go get github.com/go-ozzo/ozzo-validation`

resulted in a 3.X version to be downloaded which did not have this function. Runnning

`go get github.com/go-ozzo/ozzo-validation/v4` 

fixed my issue

**Comment by qiangxue** [comment]
I can't reproduce the "go get" issue... Anyway, glad to hear that you have solved the problem and the library is useful to you!
