### ISSUE TITLE
Govalidator not installable due to Gopkg issues

### ISSUE THREAD

**Issue by v4n** [go-ozzo/ozzo-validation#13]
When installing the dependency `gopkg.in/asaskevich/govalidator.v4` the following error occurs.

```
error: RPC failed; HTTP 301 curl 22 The requested URL returned error: 301
fatal: The remote end hung up unexpectedly
package gopkg.in/asaskevich/govalidator.v4: exit status 128
```

This is because git no longer follows redirects https://github.com/niemeyer/gopkg/issues/50 

There hasn't been any updates from the Gopkg author on the issue for a while. I would recommend to use`github.com/asaskevich/govalidator` so that this library is installable _out of the box_.

**Comment by qiangxue** [comment]
This makes perfect sense. It also makes using dependency management tools (e.g. glide, godep) much easier. Thanks!

**Comment by niemeyer** [comment]
No need to change the configuration anymore. We've changed gopkg.in itself to support the new git quirks.
