### ISSUE TITLE
Way to override the message without key

### ISSUE THREAD

**Issue by khanakia** [go-ozzo/ozzo-validation#132]
Hi ,
I am using the Validation package to return the error on the frontend as JSON and it's working great right now it returns the message like this
```
{
  "id": "cannot be blank"; 
  "name": "Please fill the name." // CUSTOM MESSAGE
}
```
But i needed to add the custom message for one field in the below format so i created a custom function to override the format. So after override the error it shows like this
```
{
  "id": "ID cannot be blank"; 
  "name": "Name Please fill the name."  // CUSTOM MESSAGE
}
```
But the issue here is now i want the `Name Please` to `Please` only and i tried every way i cannot workaround this. Because there is now way to tell that Error Type is Custom or Default.

So i thought may be you can help me regarding this.

Here' s the example link https://play.golang.org/p/Qpg3Z0FmbPj

```go
package main

import (
	"encoding/json"
	"fmt"
	"log"
	"strings"

	validation "github.com/go-ozzo/ozzo-validation"
)

func PrintToJSON(val interface{}) {
	b, err := json.MarshalIndent(val, "", "  ")
	if err != nil {
		log.Fatal(err)
	}
	fmt.Println(string(b))

}

type ErrorObject struct {
	Field   string `json:"field"`
	Message string `json:"message"`
}

func ErroObjToArray(errors error) []interface{} {
	if errors == nil {
		return []interface{}{}
	}

	var errs []interface{}

	i := 0
	for field, v := range errors.(validation.Errors) {
		message := strings.Title(field) + " " + v.Error()
		errs = append(errs, &ErrorObject{
			Field:   field,
			Message: message,
		})

		i++
	}

	return errs
}

type Item struct {
	ID   uint   `json:"id"`
	Name string `json:"name"`
}

func (a Item) Validate() ([]interface{}, error) {
	var rules []*validation.FieldRules
	rules = []*validation.FieldRules{
		validation.Field(&a.ID, validation.Required),
		validation.Field(&a.Name, validation.Required.Error("Please fill the name")),
	}

	error := validation.ValidateStruct(&a, rules...)
	data := ErroObjToArray(error)

	return data, error
}

func main() {
	a := Item{}

	data, _ := a.Validate()
	PrintToJSON(data)
}

```

RETURNS:
```
[
  {
    "field": "id",
    "message": "Id cannot be blank"
  },
  {
    "field": "name",
    "message": "Name Please fill the name"
  }
]
```

**Comment by qiangxue** [comment]
It seems you want to differentiate custom error messages from default error messages. I don't have good solutions for this. One suggestion is that you create a message map which contains all the custom messages. Then in ErroObjToArray, you check if a message is found in the map to decide whether to prefix the field.

**Comment by khanakia** [comment]
I understand. Thanks @qiangxue
