### ISSUE TITLE
Comparing Struct Variables

### ISSUE THREAD

**Issue by ahmetkucuk** [go-ozzo/ozzo-validation#14]
I am trying to validate a struct that has start time and end time as variables. I implemented following to do this. Is there any simpler way to compare those values? If not, this might be a good feature to have.
```

type TimeRange struct {
	start time.Time
	end time.Time
}

type dateRule struct {
	message  string
	timeRange TimeRange
}


// Error sets the error message for the rule.
func (v *dateRule) Error(message string) *dateRule {
	return &dateRule{
		message: message,
		timeRange: v.timeRange,
	}
}

// Validate checks if the given value is valid or not.
func (v *dateRule) Validate(value interface{}) error {
	timeRange := v.timeRange
	if timeRange.start.After(timeRange.end) {
		return errors.New(v.message)
	}
	return nil
}
//Validation Rules
func (r TemporalRequest) Validate() error {

	var sTime, err1 = utils.ParseDatetime(r.StartTime)

	if err1 != nil {
		return err1
	}
	var eTime, err2 = utils.ParseDatetime(r.EndTime)

	if err2 != nil {
		return err2
	}

	return validation.ValidateStruct(&r,
		validation.Field(&r.StartTime, &dateRule{message: "Start Time should be before end time", timeRange:TimeRange{start:sTime, end:eTime}}),
	)
}
```

**Comment by qiangxue** [comment]
Are you trying to validate a datetime string or Time object? If the former, the built-in `Date` validator can do what you want.

**Comment by ahmetkucuk** [comment]
It is not about validation of time or datetime string. I am trying to validate two variables relative to each other. Value of StartTime variable should be before value of EndTime. Basicly, I am trying to ask "what should be done if validity criteria of an variable depends on value of another variable in the struct?"

Time should be valid for sure but this is not my point.

**Comment by qiangxue** [comment]
I see. The `Field` function only deals with a single struct field. You cannot use it for two or more fields. If you need to validate a field against another, you can do something like the following (please update to the latest version):

```go
return validation.ValidateStruct(&r,
    validation.Field(&r.dateTo, validation.Min(r.dateFrom)),
)
```

**Comment by ahmetkucuk** [comment]
Thank you! This seems good. In my case, I need a wrapper function around the field. I have updated my first post for future reference.
