### ISSUE TITLE
LengthOfValue length of Chinese is wrong

### ISSUE THREAD

**Issue by liuaiyuan** [go-ozzo/ozzo-validation#149]
```go
  var str = "hello"
  length, _ := validation.LengthOfValue(str)

  fmt.Println(length) // output: 5 ✅

  fmt.Println(utf8.RuneCountInString(str))  // output: 5 ✅
```

```go
  var str = "你好"
  length, _ := validation.LengthOfValue(str)

  fmt.Println(length) // output: 6 ❌

  fmt.Println(utf8.RuneCountInString(str))  // output: 2 ✅
```

**Comment by qiangxue** [comment]
This is expected because `LengthOfValue` returns the byte length.
To validate the rune length, use [RuneLength](https://github.com/go-ozzo/ozzo-validation/blob/master/length.go#L32)

**Comment by liuaiyuan** [comment]
> This is expected because `LengthOfValue` returns the byte length.
> To validate the rune length, use [RuneLength](https://github.com/go-ozzo/ozzo-validation/blob/master/length.go#L32)

ok,thank you!!!!
