### ISSUE TITLE
Question `Marshaling vs validation`

### ISSUE THREAD

**Issue by Kiura** [go-ozzo/ozzo-validation#19]
There are two common ways for validation in go (at least that I know of):
1) using tags (eg govalidator)
2) using explicit validation (like this library)

Both good libraries, but both require using a `Validate()` function and checking error before using the struct, which is IMO not very convenient having to check every time the struct is used.

I was having this idea of moving validation into custom Unmarshaller. 

```golang
package main

import (
	"encoding/json"
        "github.com/go-ozzo/ozzo-validation"
	"fmt"
)

type Person struct {
	Name string `"json:name,omitempty"`
	Age  int    `"json:age,omitempty"`
}

func (p *Person) UnmarshalJSON(b []byte) error {
	type Alias Person
	alias := &Alias{}
	err := json.Unmarshal(b, alias)
	if err != nil {
	    return err
	}
	*p = Person(*alias)
	
        // define error checks here
	if p.Age < 18 {
	    return fmt.Errorf("Age must be more than 18")
	}
        // or fields could be validated by using this library 
        return validation.ValidateStruct(p,
            // Age must be more than 18
            validation.Field(p.Age, validation.Min(18)),
        )
	
	return err
}

func main() {

	jsonPerson := []byte(`{"name":"Joye", "age":17}`)
	person := &Person{}
	if err := json.Unmarshal(jsonPerson, person); err != nil {
	    fmt.Println("error decoding json into Person: %v", err)
	    return
	}

	fmt.Println(person)

}
```

it just seems more convenient (having to just unmarshal rather than validate and unmarshal) also it is easier to set a default value.

could you correct me if I am mistaking or forgeting something

**Comment by qiangxue** [comment]
I think your design makes a lot of sense if you are unmarshaling from user input data (or any input data that is not trustable). If you are unmarshaling from trusted data, then doing validation within unmarshaling is not necessary and could be a performance hit when there are a lot of data to be unmarshaled. 

So ultimately, the Validate method is more like a building block that you can choose to call it within or outside of the unmarshal process, depending on your use scenarios.

**Comment by Kiura** [comment]
Indeed, the library provides more options and is covers more use cases (my idea was for one case). Thx for clarification!
