### ISSUE TITLE
Validation Errors should use JSON tag values as the error keys when marshalling. 

### ISSUE THREAD

**Issue by v4n** [go-ozzo/ozzo-validation#2]
Related to https://github.com/go-ozzo/ozzo-validation/pull/1, when marshalling `validation.Errors` It would be great if we can detect struct fields with the `json` tag and use that as the key in the map for `validation.Errors`.

A option for doing this is to convert `validation.Errors` to a struct that contains two fields `Errs map[string]err` & `ErrsJSON map[string]string`. `Errs` map key contains the Struct field name and `ErrsJSON` map key contains the Struct json tag value. 

Another option would be to use a custom field tag e.g. `validation` that is checked for and if specified we use it as the map key for the error message. This isn't specifically meant to be used when marshalling json.

@qiangxue thoughts?

**Comment by qiangxue** [comment]
Very reasonable requirement. I like your second option better as it is not JSON specific.
