### ISSUE TITLE
Support validating embedded structs

### ISSUE THREAD

**Issue by noonien** [go-ozzo/ozzo-validation#24]
Considering the following:
```language:go
type ListingOptions struct {
	Offset    int    `json:"offset"`
	Limit     int    `json:"limit"`
	OrderBy   string `json:"order_by"`
	OrderDesc bool   `json:"order_desc"`
}

func (l ListingOptions) Validate() error {
	return validation.ValidateStruct(&l,
		// Offset should be a positive number
		validation.Field(&l.Offset, validation.Min(0)),
		// Limit should be between 10 and 50
		validation.Field(&l.Limit, validation.Min(10), validation.Max(50)),
	)
}

type BookListingOptions struct {
	UserID   int             `json:"user_id"`
	Status   []string       `json:"status"`

	ListingOptions
}

func (l BookListingOptions) Validate() error {
	validOrderColumns := []string{
		"name", "status", "created_at", "updated_at",
	}

	return validation.ValidateStruct(&l,
		// UserID should be a positive number
		validation.Field(&l.UserID, validation.Min(0)),
		// Status should be a valid book status
		validation.Field(&l.Status, validation.In("open", "closed")),
		// ListingOptions.Order should be a valid order clause
		validation.Field(&l.ListingOptions.OrderBy, validation.In(validOrderColumns)),
		// ListingOptions has its own validation
		validation.Field(&l.ListingOptions),
	)
}
```

Calling `BookListingOptions{}.Validate()` returns the following error: `field #2 cannot be found in the struct`

**Comment by qiangxue** [comment]
Fixed. Please let me know if you encounter any problem. Thanks!

**Comment by raghavendra-talur** [comment]
@qiangxue I think the fix referenced does not work when the struct is declared within another struct, for example
```
type A struct {
    Member1 int
    Member2 string
    SubStruct struct {
        SubMember1 int
        SubMember2 string
    }
}
```

This gives error "field #2 cannot be found in the struct" .

**Comment by byrnedo** [comment]
@qiangxue I'm also experiencing this (on 3.5.0, go 1.11.5)

**Comment by Abhisek1994Roy** [comment]
Any solution to using go gozzo when there's a struct in another struct?

**Comment by machmum** [comment]
any update on this? Im also encounter same problem.

`
Order struct {
	Order *SomeOrder `json:"order"`
}

SomeOrder {
	SomeID interface{} `json:"some_id"`
}

var bodies = new(Order)

err = validation.ValidateStruct(bodies,
		validation.Field(
			&bodies.Order.SomeID,
			validation.Match(regex.Alphanumeric).Error("must be valid order some id"),
			validation.Required, validation.Length(5, 50)),
	)
`

above gives error "field #0 cannot be found in the struct"

**Comment by rustambek96** [comment]
any updates on this? I'm also encountering the same problem

**Comment by qiangxue** [comment]
Only anonymous struct fields can be declared in with the struct's ValidateStruct(). For non-anonymous embedded structs, you should declare their field validation rules in those structs' Validate().
