### ISSUE TITLE
Problem with validating slice struct fields

### ISSUE THREAD

**Issue by noonien** [go-ozzo/ozzo-validation#25]
The following test:

```go
func TestInStruct(t *testing.T) {
	var v struct {
		Field []string
	}
	v.Field = []string{"v1"}

	err := ValidateStruct(&v,
		Field(&v.Field, In("v1", "v2")),
	)
	if err != nil {
		t.Fatal(err)
	}
}
```

Fails with: Field: must be a valid value.

**Comment by qiangxue** [comment]
This is expected. The `In` rule checks if a value can be found in the list of prespecified values.
See the code doc below:
// Note that the value being checked and the possible range of values must be of the same type.

**Comment by noonien** [comment]
I see, how does one validate such a case though? Should In() not work with slice types?

**Comment by qiangxue** [comment]
You are trying to determine if a string slice is "in" another string slice. This is not well defined - should the former be fully included in the latter, or should it allow partial intersection? 

You will need to have a custom rule to support this check. You may refer to the `in.go` file for details. It's not very complicated.

**Comment by noonien** [comment]
Well, such a field would be valid if all elements in it are valid.
