### ISSUE TITLE
Optional field validation

### ISSUE THREAD

**Issue by MaxVoronov** [go-ozzo/ozzo-validation#3]
Hi guys.
Please advise how I can skip validation for empty fields. For example add new rule Optional:
```
return validation.StructRules{}.
	Add("Gender", validation.Optional, validation.In("Female", "Male")).
	Validate(req, attrs...)
```
If validation.IsEmpty(field) equal true then we skip validation.In(...). Else we run all next validators. I know about validation.Skip, but I did not find any examples how it use. 

Another question: how I can skip validation from custom validator? 

Thank you very much for your work.
Regards, Max

**Comment by v4n** [comment]
@MaxVoronov you can try adding an empty string to `validation.In("", "Female", "Male")`. So you check for it to be empty or a gender type.

**Comment by qiangxue** [comment]
This was actually a issue. Just checked in a fix. Please update.
You only need a single rule `validation.In` in this case. The rule will treat an empty value as valid.

**Comment by MaxVoronov** [comment]
Thank you. All works fine =)
