### ISSUE TITLE
Validate if not nil

### ISSUE THREAD

**Issue by noonien** [go-ozzo/ozzo-validation#31]
Considering the following type:
```go
type Foo struct {
    OptionalBar *string
}
```

Would it be possible to validate OptionalBar only if it's not nil?

**Comment by qiangxue** [comment]
This is the behavior for most built-in validators. See https://github.com/go-ozzo/ozzo-validation#pointers

**Comment by noonien** [comment]
Ah, my bad, I should have specified. The validator i was having an issue for is `Required`. I understand why it needs to also check for nil, but it would be great to have a version that behaves like the others.

This way it can be specified that a non-zero-value is needed for that object that it points to.

**Comment by qiangxue** [comment]
Do you mean a `required` rule that treats nil pointer as valid?

**Comment by noonien** [comment]
Yes.

**Comment by qiangxue** [comment]
Added `NilOrNotEmpty` rule. Please let me know if this works for you or not. Thanks.

**Comment by noonien** [comment]
It works great! Thanks!

**Comment by logrusorgru** [comment]
> This is the behavior for most built-in validators. See https://github.com/go-ozzo/ozzo-validation#pointers

`Each` doesn't work with a `*[]string` for example.

```
must be an iterable (map, slice or array)
```
