### ISSUE TITLE
Partial validation

### ISSUE THREAD

**Issue by nkovacs** [go-ozzo/ozzo-validation#32]
I'd like to implement a partial update in my API. I can already pass in a list of struct field names to ozzo-dbx's [ModelQuery.Update](http://godoc.org/github.com/go-ozzo/ozzo-dbx#ModelQuery.Update) method, but I can't restrict validation to just those fields. 

As a workaround, I can check the returned `Errors` map and remove all the fields I'm not interested in. But would it be possible to add a version of ValidateStruct with an include/exclude feature like ModelQuery.Update?

**Comment by qiangxue** [comment]
What about another workaround:
- build a map of field names and their corresponding validation rules
- based on the fields that you want to validate, pick up the rules to do the validation?

Here's yet another workaround if you can enumerate different validation scenarios in advance:
- create multiple versions of field validation rules, one for each scenario
- validate with the rule list for the particular scenario?

Within the package we want to avoid referencing the field names as they are error prone and cannot get help from the compiler.

**Comment by nkovacs** [comment]
I came up with a better workaround: https://play.golang.org/p/T2SyMMiLFN
I can filter the map, build the rules using the filtered map, and pass those to ValidateStruct.
The only disadvantage of this is that the receiver must be a pointer.

The scenarios are a good point, but unfortunately I can't use them in this case (the api endpoint can receive any combination of fields, the unmarshaler records which fields were received, and filters the validation results based on that).
