### ISSUE TITLE
Pre validation filters concept

### ISSUE THREAD

**Issue by autowp** [go-ozzo/ozzo-validation#36]
Example situations:
- E-mail validation requires trim extra spaces before the check.
- Phone number validation requires filter unexpected character.
- Filename validator may require ToLowerCase filter

Take a look at [zend-inputfilter](https://github.com/zendframework/zend-inputfilter) and [zend-filter](https://github.com/zendframework/zend-filter), [zend-validator](https://github.com/zendframework/zend-validator) subpackages

```php
$inputFilterConfig = [
    'amount' => [
        'filters'  => [
            ['name' => 'StringTrim']
        ],
        'validators' => [
            ['name' => 'Digits'],
            [
                'name' => 'Between',
                'options' => [
                    'min' => 1,
                    'max' => 10
                ]
            ]
        ]
    ],
    'email' => [
        'filters'  => [
            ['name' => 'StringTrim'],
            ['name' => 'ToLowerCase'],
        ],
        'validators' => [
            ['name' => 'EmailAddress']
        ]
    ]
];
```

**Comment by qiangxue** [comment]
Thanks for the suggestion. I do not have plan to support data filtering in this package, for the reason of separation of concerns. It can be in a separate package.

**Comment by ssoroka** [comment]
It's also trivial to add your own pre-filtering as part of your Validate method.
