### ISSUE TITLE
Skip further rules when Nil is found in NilOrNotEmpty Rule

### ISSUE THREAD

**Issue by raghavendra-talur** [go-ozzo/ozzo-validation#37]
This is a ask for feature where more rules are checked after NilOrNotEmpty only if it was not found to be Nil.

It would be something like:

```
validation.FIeld(&req.Favoritenumbers, validation.NilOrNotEmpty, validation.By(ValidatePrime), validation.Min(100))
```
The struct being:

```
type NewPlayer struct {
Name string `json: "id"`
JerseyNumber int `json:jersey,omitempty"`
}
```
Where JerseyNumber is optional but if provided it must be a prime number and greater than 100.

**Comment by qiangxue** [comment]
Most rules (e.g. `validation.In`) are skipped if a value is nil. You don't need `NilOrNotEmpty`.

**Comment by raghavendra-talur** [comment]
@qiangxue Thanks for the explanation. I will close this issue.
