### ISSUE TITLE
Validating database nulls types

### ISSUE THREAD

**Issue by MaxVoronov** [go-ozzo/ozzo-validation#4]
Hi team.
Please advise how I can validate types like sql.NullBool, sql.NullString, sql.NullInt64, sql.NullFloat64 or advanced packages like https://github.com/guregu/null ? For example, I try to validate:
```
import (
	"fmt"
	"gopkg.in/guregu/null.v3"
	"github.com/go-ozzo/ozzo-validation"
)

type User struct {
	Name null.String
}

func (u User) Validate(attrs ...string) error {
	return validation.StructRules{}.
		Add("Name", validation.Length(2, 25)).
		Validate(u, attrs...)
}

func main() {
	user := User{Name: null.NewString("", true)}
	if err := validation.Validate(user); err != nil {
		panic(err)
	}
	fmt.Printf("Hello %s", user.Name.String)
}
```
But receive error `cannot get the length of struct`. Should I create custom validators or exists better way?

**Comment by qiangxue** [comment]
Just added the support for validating sql.Valuer. Your problem should be resolved. Thanks.

**Comment by MaxVoronov** [comment]
Wow! So fast. Thank you very much.
