### ISSUE TITLE
Could you help to provide ozzo-widget / ozzo-grid?

### ISSUE THREAD

**Issue by ScottHuangZL** [go-ozzo/ozzo-validation#44]
Dear Qian,

I am a yii1/yii2 user too, really like that elegant framework which created by you!
In these frameworks, it provide widgets which wrap bootstrap , it is very convenient to developers, especially for the grid widget.

Could you create similar widgets for ozzo framework? It should be increase the stars! Thanks.

Regards,
Scott Huang

**Comment by qiangxue** [comment]
Thank you for using yii!
I think Go is not a good replacement of PHP in regard to being a template language. For this reason, I don't think I will work on things like widget, grid in Go.

**Comment by ScottHuangZL** [comment]
ok
