### ISSUE TITLE
VGO error when parsing go.mod

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-validation#47]
Hi! I tryed to build my app with VGO and got a error:
![image](https://user-images.githubusercontent.com/3740898/40563789-c1d91c94-606e-11e8-88c3-4c95c9961149.png)
![image](https://user-images.githubusercontent.com/3740898/40563807-d5d6b7b0-606e-11e8-8898-eb0da254d1c4.png)

**Comment by aarondl** [comment]
v3.3 is an invalid semver version (see semver spec https://semver.org/). The fix for this is simply to have the ozzo library start pushing tags that are semver compliant.

I ran into this same problem and came to request that semver tags start being used.

**Comment by qiangxue** [comment]
Thank you for reporting this issue. Just pushed a new release with properly formatted version number.

**Comment by aarondl** [comment]
Thanks!

**Comment by kolkov** [comment]
Hi! Issue not resolved!
I think we need to update all tags! ((
![image](https://user-images.githubusercontent.com/3740898/42088412-0653aa76-7ba2-11e8-894d-a36599d9bbd8.png)
