### ISSUE TITLE
How to return error properly?

### ISSUE THREAD

**Issue by kolkov** [go-ozzo/ozzo-validation#5]
How to return correct http status error from validation error?

```Go
func SaveHandler(cPtr *routing.Context) error {
	var actor models.Actor
	cPtr.Read(&actor)
	err := actor.Validate()
	if err != nil {
		return err
	}
	return actor.Save()
}
...

func (m *Actor) Save() error {
	err := db.Model(m).Insert()
	if err != nil {
		fmt.Println("Exec err:", err.Error())
	}
	return err
}
```
Return http 500, and error in json. Is it correct?

**Comment by qiangxue** [comment]
For validation errors, the correct status code should be 400. 

I suppose you are using ozzo-routing. You may use the `fault.Recovery()` middleware and set your own error handler. In the error handler, you should check the type of the error. If you see `validation.Errors`, you should  set the status code as 400.

**Comment by kolkov** [comment]
Thanks!
Can you give me some example for ozzo-routing, please!

**Comment by qiangxue** [comment]
I'm creating a restful app boilerplate in Go and will publish it possibly next week.

**Comment by kolkov** [comment]
Thanks! I want to create some more complex application example in ozzo with backend and frontend with Angular.
