### ISSUE TITLE
Should the IsEmpty check be bypassed for numbers

### ISSUE THREAD

**Issue by jesse-c** [go-ozzo/ozzo-validation#52]
```
minAllowed := 1

return validation.Validate(0,
		validation.Min(minAllowed),
		validation.Max(maxAllowed),
	)
```

I would expect an `error` from this, as 0 is less than the min value (1), but instead `nil` is returned. The issue is because `(r *ThresholdRule) Validate` does a `if isNil || IsEmpty(value) {` check. Same for `Max` (what if I want to check if my value 0 satisfies the rule of the min value being 10).

I think that _in this context_, that check shouldn't be performed. It could be conditionally performed based on reflection (as it does for other reasons).

I'm happy to make a MR to do this.

Edit: I'll add in too while I'm here, thanks for the library!

**Comment by qiangxue** [comment]
This is by design and the same applies to most rules. The trick is to add a `Required` rule if you want to make sure a non-empty value is provided. See https://github.com/go-ozzo/ozzo-validation#required-vs-not-nil

**Comment by jesse-c** [comment]
Makes sense. I think the error is just slightly misleading (`cannot be blank`).

Thanks!
