### ISSUE TITLE
How can I validation field array ?

### ISSUE THREAD

**Issue by minhthuan274** [go-ozzo/ozzo-validation#55]
I have struct like this 
```
type ReviewJson struct {
	Business string   `json:"business"  form:"business"`
	Feedback string   `json:"feedback" form:"feedback"`
	Point    int      `json:"point" form:"point"`
	Photos   []string `form:"photos[]"`
}
```
I wanna validation field Photos, for each photo has valid with MongoId.

**Comment by BitPhinix** [comment]
Same problem here. it would be nice if there was a validation.Each(slice, ...rules) validation.Any(slice, ...rules)

**Comment by AlaaAttya** [comment]
indeed +1

**Comment by adred** [comment]
+1

**Comment by JKKGBE** [comment]
You can use `validation.By(yourFunc)` and in `yourFunc` iterate over elements.

**Comment by petervandenbroek** [comment]
I've added the Each() method @BitPhinix mentioned, since I needed this type of functionality myself.

See the [pull request](https://github.com/go-ozzo/ozzo-validation/pull/71).

**Comment by bappr** [comment]
Can we close this one plz? I got worried for a minute.
GJ @petervandenbroek
