### ISSUE TITLE
Validating Arrays, Slice or Maps should point to an ID / PK

### ISSUE THREAD

**Issue by leyluj** [go-ozzo/ozzo-validation#6]
Ozzo, First of all thank you for this library.

But I encountered a challenge where by, when I am validating a slice, I wanted to show the a respective field of that struct. For example;

```go
// Provided this slice ...
addresses := []Address{
    Address{Code: "id1", State: "MD", Zip: "12345"},
    Address{Code: "id2", Street: "123 Main St", City: "Vienna", State: "VA", Zip: "12345"},
    Address{Code: "id3", City: "Unknown", State: "NC", Zip: "123"},
}
```

I should do something like this

```go
err := validation.Validate(addresses, "Code")
fmt.Println(err)
```

And it should show

 ```
ID1: (City: cannot be blank; Street: cannot be blank.); ID2: (Street: cannot be blank; Zip: must be in a valid format.).
```
How is that?

**Comment by qiangxue** [comment]
Thanks!

Are you trying to validate the `ID` field only? This is no longer supported in the latest version. You would have to write a for-loop to do it explicitly.

**Comment by leyluj** [comment]
Ok Ok.
