### ISSUE TITLE
validate struct,err message skip elements "name: " 

### ISSUE THREAD

**Issue by yumin5723** [go-ozzo/ozzo-validation#61]
how can i skip the element in err message

**Comment by yumin5723** [comment]
how to rewrite error.go function Error()?thanks

**Comment by qiangxue** [comment]
Because `validation.Errors` is a map, you can iterate the errors in it and generate your preferred error string.

**Comment by omarqe** [comment]
Tried to do this one,

```
val := validation.Errors{
    "name": validation.Validate(user.Name, validation.Required),
    "email": validation.Validate(user.Email, validation.Required, is.Email),
}

for _, e := range val {
    return e
}

return val.Format()
```

It does terminate `name:` from the error message, but the bad thing is it skips email and the rest of validation because of the return in the loop. Have no idea what else can I do. Can you provide an example of this?
