### ISSUE TITLE
Unexpected interaction of numeric zero with Min(...)

### ISSUE THREAD

**Issue by frou** [go-ozzo/ozzo-validation#62]
Is it intended behaviour that the following does not return an error?

```go
validation.Validate(0, validation.Min(10))
```

I know we can use `validation.Required` but 0 is definitely < 10 also :)

**Comment by qiangxue** [comment]
Yes. 0 is considered as an empty value. You can add a `required` rule to ensure a value is entered.

**Comment by frou** [comment]
Thank you. I starred a bunch of Go validation repos and finally am getting around to evaluating them. Your "normal code" approach is cool!

![screenshot 2018-10-24 at 17 59 03](https://user-images.githubusercontent.com/172663/47447908-91817400-d7b6-11e8-8867-08d30999520e.png)
