### ISSUE TITLE
Pointer returns

### ISSUE THREAD

**Issue by aarondl** [go-ozzo/ozzo-validation#63]
I was browsing the docs and thought that this is a great looking library. However I don't understand why the rules like `LengthRule` are returned as a pointer.

https://github.com/go-ozzo/ozzo-validation/blob/master/length.go#L48

It's my understanding that a struct that is this small belongs on the stack, and by creating all these pointers in a heavy-usage scenario like an API where many models are constantly being validated is going to create unnecessary pressure on the GC. Any reasoning behind this? Is it too late to change it?

**Comment by aarondl** [comment]
I also noticed that ValidateStruct takes pointers. Curious why that is too :)

**Comment by qiangxue** [comment]
Thanks for the suggestion! Just created a PR to address the problem.

Regarding ValidateStruct taking pointers, it's because we rely on the addresses of fields to locate the struct field reflection information.
