### ISSUE TITLE
Custom validation rule with additional parameters

### ISSUE THREAD

**Issue by wI2L** [go-ozzo/ozzo-validation#64]
Hello

The `validation.By` method offers no way to use additional parameters.
I would like to modify it to accept a varidic list of parameters after the value to validate, like so:
```go
func checkAbc(value interface{}, args ...interface{}) error {
	s, _ := value.(string)
        caseSensitive, _ := args[0].(bool)
	if !caseSensitive && s != "abc" {
		return errors.New("must be abc")
	}
	if caseSensitive && !EqualFold(s, "abc") {
		return errors.New("must be abc")
	}
	return nil
}

err := validation.Validate("xyz", validation.By(checkAbc, true))
```

What do you think about it ?

**Comment by burner-account** [comment]
Please forgive my stackoverflow-like usage of github.

My initial idea would be to not modify the 'validation.By' signature but to wrap your custom rule function.

```golang
func buildCheckABC(args ...interface{}) {
    return func checkAbc(value interface{}) error {
       // do something with 'args' and 'value'
    }
}
```
 And then call it somewhat like
```golang
err := validation.Validate("xyz", validation.By( buildCheckABC(arg1, arg2)))
```
Just an idea, not tested at all.

**Comment by payuprashantg** [comment]
I tried the same but it create cyclic import issue if I send the whole struct. (Possible way to send each field separately and handled the same in return func)
In my case, I need to validate a field by creating a HMAC using the other fields in the same struct and compare the same against the filed passed for validation.

**Comment by LindseyB** [comment]
I'm running into the same issue, has anyone figure out a solution for this?

**Comment by qiangxue** [comment]
Have you tried @burner-account's suggestion? It should work.

**Comment by LindseyB** [comment]
Oh that does work @qiangxue, thanks do you think its worth wile to add docs for this?

**Comment by qiangxue** [comment]
This is a typical usage of using closure to parameterize a function. But yes, it doesn't hurt to add an example to the docs.
