### ISSUE TITLE
validation.IN cannot parse byte arrays

### ISSUE THREAD

**Issue by ChielTimmermans** [go-ozzo/ozzo-validation#72]
The validation to check if a value can be found in a given list can not parse byte arrays. I think it is pretty easy to fix. for now i will create a custom function

**Comment by qiangxue** [comment]
Could you provide an example to explain the problem?

**Comment by ChielTimmermans** [comment]
When i run the following code 
`
	data := []byte("example")
	err := validation.Validate(data,
		validation.In([]byte("test"), []byte("test2")),
	)
	fmt.Println(err)
`
I get the error: 

`panic: runtime error: comparing uncomparable type []uint8`

**Comment by qiangxue** [comment]
Fixed. Thanks!
