### ISSUE TITLE
Validate boolean values

### ISSUE THREAD

**Issue by Narven** [go-ozzo/ozzo-validation#79]
Is there a way to validate boolean values?

Thanks

**Comment by rafa-acioly** [comment]
@Narven you can just use the typing of a struct; what exactly you want to validate?

```go
type Content struct {
    Enabled bool `json:"enabled"`
}
```

**Comment by Narven** [comment]
```
// ValidateUpdateResponseBody Provides validation for the response body on Update
func (s Stream) ValidateUpdateResponseBody() error {
	return validation.ValidateStruct(&s,
		validation.Field(&s.Title, validation.Required, validation.Length(2, 80)),
		validation.Field(&s.IsActive),
	)
}
```

**Comment by Narven** [comment]
I dont like using structs for that. Because a validation is never the same base on different conditions. If a struct on creation has some fields that are valid, the do not need to be valid when updating. or on delete

**Comment by rafa-acioly** [comment]
@Narven if the content is different for each action is better to create a struct like you show, when you use;

```go
type Content struct {
    Enabled bool `json:"enabled"`
}
```

the field `enabled` is already optional and if the payload has the key then it will be parsed, if the `enabled` is not passed the `default` is `False`, i don't think that you need a validator for `true/false`.

**Comment by qiangxue** [comment]
As answered above, you don't need to validate a value is a boolean if its type is `bool`. If you want to validate if a value is `true`, then use the `Required` rule.
