### ISSUE TITLE
validation.In

### ISSUE THREAD

**Issue by Narven** [go-ozzo/ozzo-validation#89]
Hi,

I'm trying to validate a struct that contains this validation

```
validation.Field(&bc.Priority, validation.Required, validation.In(1, 2, 3, 4).Error("must be 1, 2, 3 or 4")),
```

If I pass 1,2, 3 or 4 is always returns that error "must be 1, 2, 3 or 4"

What I'm I doing wrong?

**Comment by qiangxue** [comment]
What's the type of bc.Priority?

**Comment by Narven** [comment]
int8

**Comment by qiangxue** [comment]
The type must match that in `In`. So you should specify `validation.In(int8(1), int8(2), int8(3), int8(4))`.

**Comment by Narven** [comment]
Thanks, I will try that

**Comment by fmyxyz** [comment]
向int这种也要类型完全匹配使用起来非常不方便。

**Comment by dmitryserbin** [comment]
> The type must match that in `In`. So you should specify `validation.In(int8(1), int8(2), int8(3), int8(4))`.

it would be great to have this in the docs
