### ISSUE TITLE
Error validating integer value

### ISSUE THREAD

**Issue by hotrush** [go-ozzo/ozzo-validation#9]
```
package model

import (
    "github.com/go-ozzo/ozzo-validation"
    "github.com/go-ozzo/ozzo-validation/is"
)

type UserConfirmation struct {
	ID int64 `json:"id" meddler:"id,pk"`
	UserID int64 `json:"user_id" meddler:"user_id" validation:"user_id"`
	Type string `json:"type" meddler:"type"`
	Code string `json:"-" meddler:"code"`
	Time int32 `json:"expire" meddler:"timestamp"`
}

func (uc UserConfirmation) Validate() error {
    return validation.StructRules{}.
        Add("UserID", validation.Required, is.Int).
        Add("Type", validation.Required, validation.In("sms","email")).
        Validate(uc)
}

```

and some main.go code
```
confirmation := &model.UserConfirmation{}
_ := c.BindJSON(confirmation)
errs := confirmation.Validate()
if errs != nil {
    errs := errs.(validation.Errors)
    c.JSON(http.StatusBadRequest, gin.H{
        "errors": errs,
    })
    return
}
```

Sending integer user_id value 
```
curl -XPOST localhost:8080/api/auth/confirmation/send -d '{"user_id":4,"type":"sms"}'
{"errors":{"user_id":"must be either a string or byte slice"}}
```

It ask me to send a string.... But i need an int value. And sending a string causes struct error:
```
curl -XPOST localhost:8080/api/auth/confirmation/send -d '{"user_id":"asdsa","type":"sms"}'
{"error":"json: cannot unmarshal string into Go value of type int64"}
```

Any ideas? I'm new in go)

**Comment by qiangxue** [comment]
Since you have already declared `UserID` to be an integer, you should remove the `is.Int` rule because it doesn't make sense to validate if an integer typed value is an int (that is always true, isn't it?)

**Comment by hotrush** [comment]
Understand, thank you!

**Comment by majidalaeinia** [comment]
@qiangxue 
That's right that we expect an integer for an integer when the struct declares so, but when we pass a string we expect the package to inform the user that the parameter should be an integer, not pass the validation and get a `JSON unmarshal error`!

So, there seems to be no way validating the type of a field would be `integer` for example by this package. Not?
