### ISSUE TITLE
How to convert field validation errors to standard grpc errors ?

### ISSUE THREAD

**Issue by BimuratMukhtar** [go-ozzo/ozzo-validation#94]
I think it will be good, if you provide some guidelines how to convert validation errors to google standard grpc errors with errdetails.BadRequest.FieldViolations payload (here is article that describes how to add detail to grpc error, see topic advanced usage [good article about grpc errors](https://jbrandhorst.com/post/grpc-errors/)

**Comment by qiangxue** [comment]
Please take a look at this: https://github.com/qiangxue/go-restful-api/blob/master/internal/errors/response.go#L87
It should be similar to generate `errdetails.BadRequest.FieldViolations`.

**Comment by BimuratMukhtar** [comment]
> Please take a look at this: https://github.com/qiangxue/go-restful-api/blob/master/internal/errors/response.go#L87
> It should be similar to generate `errdetails.BadRequest.FieldViolations`.

Thank you, here implemented converter to grpc error with field validation:
`
	
    // InvalidInput creates a new grpc error response representing a data validation error (BadRequest 400).
	func InvalidInput(errs validation.Errors) error {
		st := status.New(codes.InvalidArgument, "Invalid Input")
		br := &errdetails.BadRequest{}

		for field := range errs {
			v := &errdetails.BadRequest_FieldViolation{
				Field:       field,
				Description: errs[field].Error(),
			}
			br.FieldViolations = append(br.FieldViolations, v)
		}

		st, err := st.WithDetails(br)
		if err != nil {
			return status.Error(codes.Internal, err.Error())
		}
		return st.Err()
	}
`

**Comment by qiangxue** [comment]
Thanks for sharing your implementation!
