### ISSUE TITLE
required_with

### ISSUE THREAD

**Issue by mehran-prs** [go-ozzo/ozzo-validation#95]
How do you think about `required_with_one` and `required_with_all` rules that specify some fields as `required` if other fields are not empty?
I think we really need these two rules.

Something like this:
```go
// Copyright 2016 Qiang Xue. All rights reserved.
// Use of this source code is governed by a MIT-style
// license that can be found in the LICENSE file.

package validation

// ErrInInvalid is the error that returns in case of an invalid value for "required_with" rules.
var ErrRequiredWithInvalid = NewError("validation_required_with_is_blank", "field can not be blank.")

func RequiredWithOne(values ...interface{}) RequiredWithRule {
	return RequiredWithRule{
		elements: values,
		withAll:  false,
		err:      ErrRequiredWithInvalid,
	}
}

func RequiredWithAll(values ...interface{}) RequiredWithRule {
	return RequiredWithRule{
		elements: values,
		withAll:  true,
		err:      ErrRequiredWithInvalid,
	}
}

// RequiredWithRule is a validation rule that validates if specified values is not nil, so current field is required.
type RequiredWithRule struct {
	elements []interface{}
	withAll  bool
	err      Error
}

// Validate checks if the given value is valid or not.
func (r RequiredWithRule) Validate(value interface{}) error {
	allFilled := true
	oneFilled := false

	for _, elem := range r.elements {
		elem, isNil := Indirect(elem)
		filled := !(isNil || IsEmpty(elem))

		allFilled = allFilled && filled
		oneFilled = oneFilled || filled
	}

	if (r.withAll && allFilled) || (!r.withAll && oneFilled) {
		return Validate(value, Required.ErrorObject(r.err))
	}

	return r.err
}

// Error sets the error message for the rule.
func (r RequiredWithRule) Error(message string) RequiredWithRule {
	r.err = r.err.SetMessage(message)
	return r
}

// ErrorObject sets the error struct for the rule.
func (r RequiredWithRule) ErrorObject(err Error) RequiredWithRule {
	r.err = err
	return r
}

```

**Comment by qiangxue** [comment]
Could you explain how it should be used?

**Comment by mehran-prs** [comment]
Sure.
**requiredWithOne**(we can change it to `requiredWith`): The field must be required if one of the other specified fields are present.

example:`quantity` is required if a user provides `unit`.
```go
return validation.ValidateStruct(&a,
                // unit is optional.
		validation.Field(&a.Quantity, validation.RequiredWith(&a.Unit)),
	)
```

**requiredWithAll**: The field is required only if all of the other specified fields are not empty.
example: `host` and `ip` are optional, but when the user provides both of them, needs to provide `ttl` also.
I think we can achieve this by `requiredWith` also. (`ip` is required if `host` is provided and also `ttl` is required if `ip` is provided), so we can remove this rule.

**One more rule** 
**requiredOneOf**(or `requiredWithout`): one of the provided fields is required.
Example: the user must provide either `email` or `phone`.
```go
return validation.ValidateStruct(&a,
                // email is optional, because user need to provide either `email` or `phone`
		validation.Field(&a.Phone, validation.RequiredOneOf(&a.Email)),
	)
```

**Comment by qiangxue** [comment]
Thanks for the explanation!

I think these can be thought as conditional validation, i.e., apply some validation rules only when certain conditions are met. 

You have described a common use case about conditional `Required`. How about using the following syntax instead:
```
validation.Field(&a.Quantity, validation.Required.When(a.Unit != ""))
validation.Field(&a.Phone, validation.Required.When(a.Email == ""))
```
The `When()` method takes a boolean value which determines if `Required` should be applied.

To support more generic use case about conditional validation, I'm thinking about the following new function:
```
func When(condition bool, rules ...Rule) Rule {...}
```

What do you think?

My goal is to only include common/generic rules in the library and leave special ones to applications.

**Comment by mehran-prs** [comment]
Sure!
You're right, `When` is great.
If you don't have time, I can implement it and create new PR.

**Comment by qiangxue** [comment]
To clarify it, `Required.When` is a special case of `validation.When`. That is, the following two usages are equivalent:

```
validation.Field(&a.Quantity, validation.Required.When(a.Unit != ""))
validation.Field(&a.Quantity, validation.When(a.Unit != "", validation.Required)))
```

Yes, please go ahead to implement it. Thank you for your contribution!

**Comment by qiangxue** [comment]
Implemented with https://github.com/go-ozzo/ozzo-validation/pull/96
