### ISSUE TITLE
govalidator v10 IsEmail changes

### ISSUE THREAD

**Issue by mgnsk** [go-ozzo/ozzo-validation#98]
govalidator (https://github.com/asaskevich/govalidator) v10 changed the way emails are validated.

Previously in `v9` (the version which `ozzo-validation` currently uses) there was a single `IsEmail` function that did a regex match and also checked for DNS records.
Now in `v10` they split them up, `IsEmail` matches against regex only and `IsExistingEmail` does both regex and DNS.

Are there any plans regarding this update?

**Comment by qiangxue** [comment]
Thanks for finding this out! Upgraded per request: https://github.com/go-ozzo/ozzo-validation/commit/f0cccd2ddbe5e809bdc6b8bfeb40d10ed25be3fb
