### ISSUE TITLE
check for JWT token

### ISSUE THREAD

**Issue by lesovsky** [go-ozzo/ozzo-validation#99]
Hi, thank for great and amazing project!

Is it possible to add simple check for JWT token? This check should not do a deep inspection of token's content, just something simple like:
1. String consists of 3 parts divided by comma;
2. First and second parts are base64-encoded strings;
3. Don't know how to check signature (third part), but maybe it's sufficient to check it is aplhanumeric (with hyphens and undescores) or just skip it.

Best regards

**Comment by qiangxue** [comment]
@lesovsky Thanks for the suggestion! I think this is better left to jwt library to handle the validation. As you described, the validation includes both simple format check as well as signature verification. And there's also token expiration check. All these should have been handled well by jwt libraries.
